### ISSUE TITLE
Acceso restringido al sistema

### ISSUE THREAD

**Issue by AntonioPaternina** [ISWPOLI/poli-booking#123]
**como**: dueño del sistema
**quiero**: tener acceso privilegiado a ciertas funcionalidades del sistema
**de forma que**: usuarios externos no puedan afectar mi sistema

Tareas:
- [x] proteger ciertas rutas en BackboneJS para que puedan ser accedidas según el rol del usuario en sesión

- [x] conectar roles de Spring Security con roles en Backbone

**Comment by DiegOliveros** [comment]
Antonio, las tareas deben pertenecer a la historia. No son una issue.
Utilizar el formato +[ ] ó -[ ] para cada una de las tareas dentro de una historia.

**Comment by AntonioPaternina** [comment]
de acuerdo, volví esta tarea una historia mejor.gracias
