### ISSUE TITLE
Criterios de aceptación para todas las historias en el History map

### ISSUE THREAD

**Issue by jacastrorug** [ISWPOLI/poli-booking#133]
narrativa: Crear los criterios de aceptación
como: desarrollador
quiero: Contar con los criterios de aceptación de las historias planteadas en el History map para poder realizar la valoración y el alcance de la aplicación.

Tareas:

- [x] Crear un documento formal donde especifique la historia y junto a ella los criterios de aceptación, hacer una por cada historia.

**Comment by AntonioPaternina** [comment]
hola @jacastrorug, esto ya está terminado verdad?

**Comment by jacastrorug** [comment]
Hola, si está realizada, perdón por no cerrarla.
