### ISSUE TITLE
Selección de metodología

### ISSUE THREAD

**Issue by AntonioPaternina** [ISWPOLI/poli-booking#35]
- [x] selección de metodología

**Comment by AntonioPaternina** [comment]
Hola @jhojanQuintero estamos siguiendo la metodología Scrum. Subamos aquí un documento donde se tenga una breve descripción de la metodología y una breve justificación de la razón por la que la escogimos.

**Comment by jhojanQuintero** [comment]
[Metodología de Scrum.docx](https://github.com/ISWPOLI/poli-booking/files/836945/Metodologia.de.Scrum.docx)
