### ISSUE TITLE
Perfilado del equipo de trabajo

### ISSUE THREAD

**Issue by AntonioPaternina** [ISWPOLI/poli-booking#36]
- [ ] perfilado del equipo de trabajo

**Comment by AntonioPaternina** [comment]
Hola @jhojanQuintero creo que aquí podemos adjuntar archivos, entonces subamos aquí un documento donde estén especificados los roles de cada uno de los integrantes.

**Comment by jhojanQuintero** [comment]
[PERFILADO DEL EQUIPO.docx](https://github.com/ISWPOLI/poli-booking/files/838712/PERFILADO.DEL.EQUIPO.docx)

**Comment by AntonioPaternina** [comment]
gracias @jhojanQuintero, porfa no olvides cerrar las tareas una vez completadas. esta la cierro yo entonces. saludos
