### ISSUE TITLE
Crear JavaScript de la vista de Home, con los eventos a capturar.

### ISSUE THREAD

**Issue by jacastrorug** [ISWPOLI/poli-booking#40]
Debes crear un archivo JavaScript (View en la estructura backbone) el cual servira para invocar el template de home cuando sea llamado, ademas de eso agregar los eventos de los botones que la vista disponga con las funcionalidades necesarias.

**Comment by AntonioPaternina** [comment]
@jacastrorug @davidhmaciasv le voy a quitar la etiqueta de característica ya que no está dentro de las características que definimos. Cualquier cosa me cuentan. Saludos
