### ISSUE TITLE
Integrar todas los templates con sus respectivas vistas de JavaScript ademas de asignarles una url en el router.

### ISSUE THREAD

**Issue by jacastrorug** [ISWPOLI/poli-booking#41]
Debes hacer que todas las vistas de usuario o administrador tengan su archivo JavaScript(View en Backbone) las cuales capturen los eventos y llamen el template asignado, ademas de eso debes ir al archivo router.js y crear todas las rutas correspondientes para cuando sean invocadas por la aplicación.

**Comment by ingenieriadelsoftware** [comment]
No se realiza asignación de tareas

**Comment by AntonioPaternina** [comment]
Hola @jacastrorug voy a cerrar esta épica puesto que no está dentro de las épicas que definimos al inicio del proyecto. Supongo que esta fue una épica de prueba creada para el parcial. Si no es así por favor me lo haces saber. Saludos
